services:
  app:
    build:
      context: .
    container_name: coudstorage-app
    networks:
      - cloud-net
    depends_on:
      - psql
      - minio
      - redis
    env_file:
      - .env
    ports:
      - '8080:8080'

  psql:
    image: postgres:16.3
    container_name: psql-cloud
    networks:
      - cloud-net
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z
    container_name: minio-cloud
    networks:
      - cloud-net
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
    volumes:
      - ${HOME}/minio-cloud:/~/minio

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    container_name: redis-cloud
    networks:
      - cloud-net

networks:
  cloud-net:
    driver: bridge