services:

  psql:
    image: postgres:16.3
    container_name: psql-cloud
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - psql-cloud-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z
    container_name: minio-cloud
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - ${HOME}/minio-cloud:/~/minio

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    container_name: redis-cloud
    ports:
      - '6379:6379'

volumes:
  psql-cloud-data: